### Buscar todo os ID
GET http://localhost:3333/user/

### Buscar EXTRATO COM ID
GET http://localhost:3333/user/

### Alterar CADASTRO DO USUARIO NO BANCO
PUT  http://localhost:3333/user/alterar/
content-type: application/json

{
   "nome": "Thalia Thaiane",
    "endereco": "Rua Rio de Janeiro",
    "cpf": "100.300.548.20",
    "saldo": 110,
    "transacao":[]
}

### Inserir Informação DO USUARIO NO BANCO
POST http://localhost:3333/user/
content-type: application/json

{
    "nome": "Thalia",
    "endereco": "Rua Dos Pinhais",
    "cpf": "100.300.548.20",
    "saldo": 110,
    "transacao":[]
}

### Deletar USUARIO DO BANCO
DELETE  http://localhost:3333/user/

### SAQUE
PUT  http://localhost:3333/user/sacar/
content-type: application/json

{
    "name": "Thalia Thaiane",
    "transacao":[{
      "valor":50
    }]
}

### DEPOSITO
PUT  http://localhost:3333/user/depositar/
content-type: application/json

{

    "name": "Thalia Thaiane",
    "transacao":[{
    "valor":20
    }]
}

